### ISSUE TITLE
LogRedacting panics on nil value logging

### ISSUE THREAD

**Issue by aloknnikhil** [ligato/cn-infra#427]
With the new log redaction feature, we are seeing crashes in the logger when one of the values to be logged is nil

Example:
```
log.Debugf("RetrieveInterfaceStatusFromRamCache: %+v", ifStatus)
```

This panics if ifStatus is a pointer and is nil. It's completely valid in some cases to have a "nil" printed to the log.

**Comment by ondrej-fabry** [comment]
Please post the panic output with stack trace.
